### ISSUE TITLE
Plotting error with nonsample data

### ISSUE THREAD

**Issue by ecarr6771** [blekhmanlab/biomehorizon#14]
I got the following error when running `horizonplot(paramList)` with nonsample data, which I assume has to do with input data formatting. Is this an error that's been seen before? Could you provide insight into where to look for the cause?
`Error in `[<-`:
! Assigned data `unlist(otudata[i, 2:(ncol(otudata) - 1)]) - ...` must be compatible with row subscript `i`.
✖ 1 row must be assigned.
✖ Assigned data has 3 rows.
ℹ Row updates require a list value. Do you need `list()` or `as.list()`?
Caused by error in `vectbl_recycle_rhs_rows()`:
! Can't recycle input of size 3 to size 1.
Backtrace:
  1. biomehorizon::horizonplot(paramList)
 14. tibble (local) `<fn>`(`<vctrs___>`)
 15. tibble:::vectbl_recycle_rhs_rows(value, length(i), i_arg, value_arg, call)
Error in `[<-`(`*tmp*`, i, 2:(ncol(otudata) - 1), value = c(ST_DNA_1 = 0.481265039532485, :

✖ 1 row must be assigned.
✖ Assigned data has 3 rows.
ℹ Row updates require a list value. Do you need `list()` or `as.list()`?
Caused by error in `vectbl_recycle_rhs_rows()`:
! Can't recycle input of size 3 to size 1.`

**Comment by isaacfink21** [comment]
Thanks for posting your solution, @ecarr6771! Feel free to reach out if you have any additional questions.
