### ISSUE TITLE
colour error

### ISSUE THREAD

**Issue by danfrks** [blekhmanlab/biomehorizon#16]
Dear authors,

Thank you for the brilliant package. I have a slight issue: I cannot change the colour palette.

`CC_hp <- horizonplot(paramList, aesthetics = horizonaes(title = "", xlabel = "Time (days)",
                                                        ylabel = "Taxa with >1% abundance\nfound in >10% of samples",
                                                        legendTitle = "Quartiles Relative to Taxon Median",
                                                        legendPosition = "bottom",
                                                        col.bands = brewer.pal(8, "PiYG")))`
The error:
`Error in nchar(col.bands) != 7 || substr(col.bands, 1, 1) != "#" : 
  'length = 8' in coercion to 'logical(1)'`

This doesn't change if I change the `nbands` parameter nor if I change the number of colour variables.
It might be something really simple I am missing - I thought I'd ask.

Thanks in advance

Daniel

**Comment by isaacfink21** [comment]
Hi @danfrks! Thanks for catching this - I just pushed a [commit](https://github.com/blekhmanlab/biomehorizon/commit/4c8a5fe7ff6d415679df43a676f05d723e13436d) that should fix this issue if you pull the latest version of the master branch. Let me know if you're still running into any issues.

**Comment by danfrks** [comment]
Thanks for the quick response! It works.

Best wishes!
